### ISSUE TITLE
Provide template as String

### ISSUE THREAD

**Issue by esiqveland** [tiagobento/watertemplate-engine#16]
Would it be possible to provide the template as a String (or InputStream) instead of a fixed filepath?

**Comment by tiagobento** [comment]
What's your use case? Water was designed to be not as permissive as other template engines and therefore ensure that you'll have less surprises concerning code design choices. However, there are many cases for which Water won't be a good choice. Can you share with us why you can't put your template in a file?

**Comment by esiqveland** [comment]
Well, more concretely our email templates are yaml files with a subject line and content:
```
subject: 'A fitting subject line'

content: |
   <html>
     ...
   </html>
```

but think the templates are datastructures themselves, and not plain text, so cant be used directly.

And Water seems to be a good fit for bundling templates with regards to type-safety and some nice java8 features.

Giving a templating library a string or inputstream to render does not seem unreasonable, and simplifies testing.
Think that you can separately test template loading and template rendering.

**Comment by tiagobento** [comment]
I understand. That is certainly an use case I didn't think about while designing Water, but it does seem legit.

Let's say you have a file called `email.yml` and that this file respects the structure you described. If you're using i18n, I assume the subject will change too, right? So why not make the entire `email.yml` be a Water Template? If you're not using i18n, making `email.yml` be a Template won't be a problem either, because yml files do not conflict with Water's syntax.

I'm really trying to help you with your scenario because I also think Water is a good fit  with regards to type-safety and integration with Java 8, but something I really don't want to do is something like a StringTemplate where you can create a Template outside the bounds of a class.

**Comment by esiqveland** [comment]
I did not think of that. It would probably work to make the entire template a Water Template.
I'll look into that tomorrow.

**Comment by tiagobento** [comment]
Nice! Feel free to share your results here :)

**Comment by esiqveland** [comment]
Didn't have time yesterday, but I got it working at least.
I have a water template that reads the yaml file as texts, then after rendering to a string, parses it into the yaml-template class for sending.
